name: Checks

on:
  push

defaults:
  run:
    shell: bash

jobs:
  # structure inspired by the mypy test suite
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint (MacOS)
            os: macos-latest
            python: 3.9
            setup: true
            command: tox -e lint
          - name: Tests (MacOS)
            os: macos-latest
            python: 3.9
            setup: true
            command: tox -e tests
          - name: Type check (MacOS)
            os: macos-latest
            python: 3.9
            setup: true
            command: tox -e type
          - name: Docker build (Ubuntu)
            os: ubuntu-latest
            setup: false
            command: docker build -t pythonapp .
          - name: Package Install (MacOS, 3.8)
            os: macos-latest
            python: 3.8
            setup: true
            command: tox
          - name: Package Install (MacOS, 3.9)
            os: macos-latest
            python: 3.9
            setup: true
            command: tox
    name: ${{ matrix.name }}
    steps:
      - if: ${{ matrix.setup }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - if: ${{ matrix.setup }}
        run: python -m pip install tox tox-venv
      - uses: actions/checkout@v2
      - name: Rename the package
        run: bash tools/rename.bash coolmathtools example_python_package
      - run: ${{ matrix.command }}
