name: Checks

on:
  push

defaults:
  run:
    shell: bash

jobs:
  # structure inspired by the mypy test suite
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Tests on Ubuntu
            os: ubuntu-latest
            setup: true
            command: tox -e tests
          - name: Tests on MacOS
            os: macos-latest
            setup: true
            command: tox -e tests
          - name: Type check on Ubuntu
            os: ubuntu-latest
            setup: true
            command: tox -e type
          - name: Type check on MacOS
            os: macos-latest
            setup: true
            command: tox -e type
          - name: Docker build on Ubuntu
            os: ubuntu-latest
            command: docker build -t pythonapp .
    name: ${{ matrix.name }}
    steps:
      - if: ${{ matrix.setup }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - if: ${{ matrix.setup }}
        run: python -m pip install tox tox-venv
      - uses: actions/checkout@v2
      - run: ${{ matrix.command }}
