name: Checks

on:
  push

defaults:
  run:
    shell: bash

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pipenv
      - uses: actions/checkout@v2
      - run: pipenv install --dev
      - run: pipenv run typecheck
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pipenv
      - uses: actions/checkout@v2
      - run: pipenv install --dev
      - run: pipenv run tests
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t pythonapp .
